version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@expo/metro-config"
    versions:
    - 0.1.57
    - 0.1.58
    - 0.1.59
    - 0.1.60
    - 0.1.61
    - 0.1.62
    - 0.1.64
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
  - dependency-name: react-native-screens
    versions:
    - 2.18.1
    - 3.0.0
    - 3.1.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: react-native-reanimated
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: expo-sensors
    versions:
    - 10.0.0
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: expo-splash-screen
    versions:
    - 0.9.0
  - dependency-name: expo-font
    versions:
    - 9.0.0
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.2.0
  - dependency-name: expo-permissions
    versions:
    - 11.0.0
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: husky
    versions:
    - 5.1.3
