export default {
  homePageTitle: 'Choose your sign',
  signs: {
    aquarius: 'Aquarius',
    aries: 'Aries',
    cancer: 'Cancer',
    capricorn: 'Capricornius',
    gemini: 'Gemini',
    leo: 'Leo',
    libra: 'Libra',
    pisces: 'Pisces',
    sagittarius: 'Sagittarius',
    scorpio: 'Scorpius',
    taurus: 'Taurus',
    virgo: 'Virgo',
  },
  signsDatePeriods: {
    aquarius: '21 January - 19 February',
    aries: '21 March - 20 April',
    cancer: '22 June - 22 July',
    capricorn: 'Dec 23 - Jan 20',
    gemini: '22 May - 21 June',
    leo: '23 July - 21 August',
    libra: '24 September - 23 October',
    pisces: '20 February - 20 March',
    sagittarius: '23 November - 22 December',
    scorpio: '24 October - 22 November',
    taurus: '21 Apr - 21 May',
    virgo: '22 August - 23 September',
  },
  linkTo: 'Information provided by ignio.com',
};
