export default {
  homePageTitle: 'Выбирите ваш знак',
  signs: {
    aquarius: 'Водолей',
    aries: 'Овен',
    cancer: 'Рак',
    capricornius: 'Козерог',
    gemini: 'Близнецы',
    leo: 'Лев',
    libra: 'Весы',
    pisces: 'Рыбы',
    sagittariusSymbol: 'Стрелец',
    scorpius: 'Скорпион',
    taurus: 'Телец',
    virgo: 'Дева',
  },
  signsDatePeriods: {
    aquarius: '21 Января — 19 Февраля',
    aries: '21 Марта — 20 Aпреля',
    cancer: '22 Июня — 22 Июля',
    capricornius: '23 Декабря — 20 Января',
    gemini: '22 Мая — 21 Июня',
    leo: '23 Июля — 21 Августа',
    libra: '24 Сентября — 23 Октября',
    pisces: '20 Февраля — 20 Марта',
    sagittariusSymbol: '23 Ноября — 22 Декабря',
    scorpius: '24 Октября — 22 Ноября',
    taurus: '21 Aпреля — 21 Мая',
    virgo: '22 Августа — 23 Сентября',
  },
};
